/*
 * Copyright (c) 2022  The AdvantEDGE Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * AdvantEDGE Bandwidth Management API
 * Bandwidth Management Sercice is AdvantEDGE's implementation of [ETSI MEC ISG MEC015 Traffic Management APIs](https://www.etsi.org/deliver/etsi_gs/MEC/001_099/015/02.02.01_60/gs_MEC015v020201p.pdf) <p>[Copyright (c) ETSI 2017](https://forge.etsi.org/etsi-forge-copyright-notice.txt) <p>**Micro-service**<br>[meep-tm](https://github.com/InterDigitalInc/AdvantEDGE/tree/master/go-apps/meep-tm/server/bwm) <p>**Type & Usage**<br>Edge Service used by edge applications that want to get information about BWM Info and Session(s) in the network <p>**Note**<br>AdvantEDGE supports all Bandwidth Management API endpoints.
 *
 * OpenAPI spec version: 2.2.1
 * Contact: AdvantEDGE@InterDigital.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AdvantEdgeBandwidthManagementApi) {
      root.AdvantEdgeBandwidthManagementApi = {};
    }
    root.AdvantEdgeBandwidthManagementApi.BwInfoDeltasSessionFilter = factory(root.AdvantEdgeBandwidthManagementApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The BwInfoDeltasSessionFilter model module.
   * @module model/BwInfoDeltasSessionFilter
   * @version 2.2.1
   */

  /**
   * Constructs a new <code>BwInfoDeltasSessionFilter</code>.
   * @alias module:model/BwInfoDeltasSessionFilter
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BwInfoDeltasSessionFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BwInfoDeltasSessionFilter} obj Optional instance to populate.
   * @return {module:model/BwInfoDeltasSessionFilter} The populated <code>BwInfoDeltasSessionFilter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('dstAddress'))
        obj.dstAddress = ApiClient.convertToType(data['dstAddress'], 'String');
      if (data.hasOwnProperty('dstPort'))
        obj.dstPort = ApiClient.convertToType(data['dstPort'], 'String');
      if (data.hasOwnProperty('protocol'))
        obj.protocol = ApiClient.convertToType(data['protocol'], 'String');
      if (data.hasOwnProperty('sourceIp'))
        obj.sourceIp = ApiClient.convertToType(data['sourceIp'], 'String');
      if (data.hasOwnProperty('sourcePort'))
        obj.sourcePort = ApiClient.convertToType(data['sourcePort'], 'String');
    }
    return obj;
  }

  /**
   * Destination address identity of session. The string for a IPv4 address shall be formatted in the \"dotted decimal\" notation as defined in IETF RFC 1166 [10]. The string for a IPv6 address shall be formatted according to clause 4 of IETF RFC 5952 [11], with in CIDR notation [12] used to provide the routing prefix.
   * @member {String} dstAddress
   */
  exports.prototype.dstAddress = undefined;

  /**
   * Destination port identity of session
   * @member {String} dstPort
   */
  exports.prototype.dstPort = undefined;

  /**
   * Protocol number
   * @member {String} protocol
   */
  exports.prototype.protocol = undefined;

  /**
   * Source address identity of session. The string for a IPv4 address shall be formatted in the \"dotted decimal\" notation as defined in IETF RFC 1166 [10]. The string for a IPv6 address shall be formatted according to clause 4 of IETF RFC 5952 [11], with in CIDR notation [12] used to provide the routing prefix.
   * @member {String} sourceIp
   */
  exports.prototype.sourceIp = undefined;

  /**
   * Source port identity of session 
   * @member {String} sourcePort
   */
  exports.prototype.sourcePort = undefined;

  return exports;

}));
