/*
 * Copyright (c) 2022  The AdvantEDGE Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * AdvantEDGE Bandwidth Management API
 * Bandwidth Management Sercice is AdvantEDGE's implementation of [ETSI MEC ISG MEC015 Traffic Management APIs](https://www.etsi.org/deliver/etsi_gs/MEC/001_099/015/02.02.01_60/gs_MEC015v020201p.pdf) <p>[Copyright (c) ETSI 2017](https://forge.etsi.org/etsi-forge-copyright-notice.txt) <p>**Micro-service**<br>[meep-tm](https://github.com/InterDigitalInc/AdvantEDGE/tree/master/go-apps/meep-tm/server/bwm) <p>**Type & Usage**<br>Edge Service used by edge applications that want to get information about BWM Info and Session(s) in the network <p>**Note**<br>AdvantEDGE supports all Bandwidth Management API endpoints.
 *
 * OpenAPI spec version: 2.2.1
 * Contact: AdvantEDGE@InterDigital.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BwInfoDeltasSessionFilter'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BwInfoDeltasSessionFilter'));
  } else {
    // Browser globals (root is window)
    if (!root.AdvantEdgeBandwidthManagementApi) {
      root.AdvantEdgeBandwidthManagementApi = {};
    }
    root.AdvantEdgeBandwidthManagementApi.BwInfoDeltas = factory(root.AdvantEdgeBandwidthManagementApi.ApiClient, root.AdvantEdgeBandwidthManagementApi.BwInfoDeltasSessionFilter);
  }
}(this, function(ApiClient, BwInfoDeltasSessionFilter) {
  'use strict';

  /**
   * The BwInfoDeltas model module.
   * @module model/BwInfoDeltas
   * @version 2.2.1
   */

  /**
   * Constructs a new <code>BwInfoDeltas</code>.
   * @alias module:model/BwInfoDeltas
   * @class
   * @param appInsId {String} Application instance identifier
   * @param requestType {module:model/BwInfoDeltas.RequestTypeEnum} Numeric value (0 - 255) corresponding to specific type of consumer as following: 0 = APPLICATION_SPECIFIC_BW_ALLOCATION 1 = SESSION_SPECIFIC_BW_ALLOCATION
   */
  var exports = function(appInsId, requestType) {
    this.appInsId = appInsId;
    this.requestType = requestType;
  };

  /**
   * Constructs a <code>BwInfoDeltas</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BwInfoDeltas} obj Optional instance to populate.
   * @return {module:model/BwInfoDeltas} The populated <code>BwInfoDeltas</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('allocationId'))
        obj.allocationId = ApiClient.convertToType(data['allocationId'], 'String');
      if (data.hasOwnProperty('allocationDirection'))
        obj.allocationDirection = ApiClient.convertToType(data['allocationDirection'], 'String');
      if (data.hasOwnProperty('appInsId'))
        obj.appInsId = ApiClient.convertToType(data['appInsId'], 'String');
      if (data.hasOwnProperty('fixedAllocation'))
        obj.fixedAllocation = ApiClient.convertToType(data['fixedAllocation'], 'String');
      if (data.hasOwnProperty('fixedBWPriority'))
        obj.fixedBWPriority = ApiClient.convertToType(data['fixedBWPriority'], 'String');
      if (data.hasOwnProperty('requestType'))
        obj.requestType = ApiClient.convertToType(data['requestType'], 'Number');
      if (data.hasOwnProperty('sessionFilter'))
        obj.sessionFilter = ApiClient.convertToType(data['sessionFilter'], [BwInfoDeltasSessionFilter]);
    }
    return obj;
  }

  /**
   * Bandwidth allocation instance identifier
   * @member {String} allocationId
   */
  exports.prototype.allocationId = undefined;

  /**
   * The direction of the requested BW allocation: 00 = Downlink (towards the UE) 01 = Uplink (towards the application/session) 10 = Symmetrical
   * @member {String} allocationDirection
   */
  exports.prototype.allocationDirection = undefined;

  /**
   * Application instance identifier
   * @member {String} appInsId
   */
  exports.prototype.appInsId = undefined;

  /**
   * Size of requested fixed BW allocation in [bps]
   * @member {String} fixedAllocation
   */
  exports.prototype.fixedAllocation = undefined;

  /**
   * Indicates the allocation priority when dealing with several applications or sessions in parallel. Values are not defined in the present document
   * @member {module:model/BwInfoDeltas.FixedBWPriorityEnum} fixedBWPriority
   */
  exports.prototype.fixedBWPriority = undefined;

  /**
   * Numeric value (0 - 255) corresponding to specific type of consumer as following: 0 = APPLICATION_SPECIFIC_BW_ALLOCATION 1 = SESSION_SPECIFIC_BW_ALLOCATION
   * @member {module:model/BwInfoDeltas.RequestTypeEnum} requestType
   */
  exports.prototype.requestType = undefined;

  /**
   * Session filtering criteria, applicable when requestType is set as SESSION_SPECIFIC_BW_ALLOCATION. Any filtering criteria shall define a single session only. In case multiple sessions match sessionFilter the request shall be rejected
   * @member {Array.<module:model/BwInfoDeltasSessionFilter>} sessionFilter
   */
  exports.prototype.sessionFilter = undefined;


  /**
   * Allowed values for the <code>fixedBWPriority</code> property.
   * @enum {String}
   * @readonly
   */
  exports.FixedBWPriorityEnum = {
    /**
     * value: "SEE DESCRIPTION"
     * @const
     */
    SEE_DESCRIPTION: "SEE DESCRIPTION"
  };


  /**
   * Allowed values for the <code>requestType</code> property.
   * @enum {Number}
   * @readonly
   */
  exports.RequestTypeEnum = {
    /**
     * value: 0
     * @const
     */
    _0: 0,

    /**
     * value: 1
     * @const
     */
    _1: 1
  };

  return exports;

}));
